const items = [
  {
    inv_nr: "FV/1/26",
    status: "draft",
    ksef: "not_sent",
    is_new: false,
    date: "2026-01-03",
    buyer: "Tech Solutions Sp. z o.o.",
    sum_gross: 1230.5,
    pay_status: "unpaid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/2/26",
    status: "issued",
    ksef: "sent",
    is_new: false,
    date: "2026-01-05",
    buyer: "ABC Logistics S.A.",
    sum_gross: 845.0,
    pay_status: "paid",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/3/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-07",
    buyer: "Green Energy Polska Sp. z o.o.",
    sum_gross: 4520.9,
    pay_status: "paid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/4/26",
    status: "draft",
    ksef: "not_sent",
    is_new: false,
    date: "2026-01-09",
    buyer: "Nova Budownictwo Sp. z o.o.",
    sum_gross: 2100.0,
    pay_status: "unpaid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/5/26",
    status: "issued",
    ksef: "rejected",
    is_new: false,
    date: "2026-01-10",
    buyer: "Digital Wave Sp. z o.o.",
    sum_gross: 999.99,
    pay_status: "partial",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/6/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-11",
    buyer: "AutoParts Polska S.A.",
    sum_gross: 3210.75,
    pay_status: "paid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/7/26",
    status: "draft",
    ksef: "not_sent",
    is_new: false,
    date: "2026-01-12",
    buyer: "SmartHome Systems Sp. z o.o.",
    sum_gross: 540.2,
    pay_status: "unpaid",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/8/26",
    status: "issued",
    ksef: "sent",
    is_new: false,
    date: "2026-01-13",
    buyer: "Global Trade Group Sp. z o.o.",
    sum_gross: 1820.4,
    pay_status: "partial",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/9/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-14",
    buyer: "PolTech Industries Sp. z o.o.",
    sum_gross: 760.0,
    pay_status: "paid",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/10/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-15",
    buyer: "BlueSky Marketing Sp. z o.o.",
    sum_gross: 1340.55,
    pay_status: "unpaid",
    pay_type: "bank_transfer",
  },

  // nowe z KSeF
  {
    inv_nr: "FV/11/26",
    status: "issued",
    ksef: "accepted",
    is_new: true,
    date: "2026-01-16",
    buyer: "Omega Consulting Sp. z o.o.",
    sum_gross: 2890.0,
    pay_status: "unpaid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/12/26",
    status: "issued",
    ksef: "accepted",
    is_new: true,
    date: "2026-01-17",
    buyer: "Delta Systems S.A.",
    sum_gross: 1560.3,
    pay_status: "partial",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/13/26",
    status: "issued",
    ksef: "accepted",
    is_new: true,
    date: "2026-01-18",
    buyer: "Baltic Trade Sp. z o.o.",
    sum_gross: 980.0,
    pay_status: "unpaid",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/16/26",
    status: "issued",
    ksef: "accepted",
    is_new: true,
    date: "2026-01-21",
    buyer: "Nordic Energy Group Sp. z o.o.",
    sum_gross: 3050.5,
    pay_status: "partial",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/17/26",
    status: "issued",
    ksef: "accepted",
    is_new: true,
    date: "2026-01-22",
    buyer: "Sigma Logistics Sp. z o.o.",
    sum_gross: 1475.9,
    pay_status: "unpaid",
    pay_type: "cash",
  },

  {
    inv_nr: "FV/14/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-19",
    buyer: "Future IT Solutions Sp. z o.o.",
    sum_gross: 4120.75,
    pay_status: "paid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/15/26",
    status: "draft",
    ksef: "not_sent",
    is_new: false,
    date: "2026-01-20",
    buyer: "EcoBuild Polska Sp. z o.o.",
    sum_gross: 2200.0,
    pay_status: "unpaid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/18/26",
    status: "issued",
    ksef: "sent",
    is_new: false,
    date: "2026-01-23",
    buyer: "Vertex Media Sp. z o.o.",
    sum_gross: 690.0,
    pay_status: "partial",
    pay_type: "cash",
  },
  {
    inv_nr: "FV/19/26",
    status: "issued",
    ksef: "accepted",
    is_new: false,
    date: "2026-01-24",
    buyer: "Quantum Robotics Sp. z o.o.",
    sum_gross: 5520.0,
    pay_status: "paid",
    pay_type: "bank_transfer",
  },
  {
    inv_nr: "FV/20/26",
    status: "draft",
    ksef: "not_sent",
    is_new: false,
    date: "2026-01-25",
    buyer: "Atlas Construction Sp. z o.o.",
    sum_gross: 1780.4,
    pay_status: "unpaid",
    pay_type: "cash",
  },
];

export default items;
